import { Container } from "../../components/layout/Container";
import { SITE_CONFIG } from "../../lib/site";

export const metadata = {
  title: "Terms of Use | MouseTester",
  description: "Terms of Use for the MouseTester website and diagnostic tools.",
  alternates: {
    canonical: '/terms',
  },
};

export default function TermsPage() {
  return (
    <>
      <div className="bg-muted/30 border-b border-border py-12">
        <Container>
          <div className="max-w-4xl">
            <h1 className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl mb-4">
              Terms of Use
            </h1>
            <p className="text-lg text-muted-foreground">
              Last updated: August 2024
            </p>
          </div>
        </Container>
      </div>

      <section className="py-12 bg-background">
        <Container>
          <div className="max-w-3xl space-y-8 text-lg text-muted-foreground leading-relaxed">
            <p>
              By accessing or using {SITE_CONFIG.name} (&quot;this website&quot;), you agree to be bound by these Terms of Use. If you do not agree with any part of these terms, you should not use this website.
            </p>
            
            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Nature of Browser-Based Tools</h2>
            <p>
              The diagnostic tools provided on this website operate entirely within your web browser. They measure the input events that are successfully routed by your operating system and web browser.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Informational Purpose Only</h2>
            <p>
              All metrics, results, and diagnostic outputs generated by this website are provided for general informational purposes only. These tools provide software-based estimates and observations, not certified hardware diagnostics. A result indicating a potential issue (such as double clicking or low polling rate) does not definitively prove hardware failure, as software settings, browser limitations, and environmental factors can heavily influence these results.
            </p>
            <p>
              You should not make purchasing, warranty, or repair decisions based solely on the results of these tools.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Acceptable Use</h2>
            <p>
              You agree to use this website only for its intended purpose of testing computer peripherals. You agree not to attempt to disrupt, exploit, or automate interactions with the website in a way that harms the infrastructure or degrades the experience for other users.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Disclaimer of Warranties</h2>
            <p>
              THIS WEBSITE AND ALL INCLUDED TOOLS ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS WITHOUT ANY WARRANTIES OF ANY KIND. WE EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF ACCURACY, RELIABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by applicable law, we shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with your access to, use of, or inability to use this website.
            </p>

            <h2 className="text-2xl font-bold text-foreground mt-8 mb-4">Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Your continued use of the website following any changes constitutes your acceptance of the new terms.
            </p>
          </div>
        </Container>
      </section>
    </>
  );
}
